default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['PLANTIFUL_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: plantiful_development

test:
  <<: *default
  database: plantiful_test

production:
  <<: *default
  database: plantiful_production
  username: plantiful
  password: <%= ENV['PLANTIFUL_DATABASE_PASSWORD'] %>
